---
variables:
  BUILDX_VERSION: "v0.17.1"

stages:
  - lint
  - build

superlinter:
  stage: lint
  tags:
    - gitlab-org-docker
  image: ghcr.io/github/super-linter:slim-v4
  script:
    - "true"
  variables:
    RUN_LOCAL: "true"
    VALIDATE_NATURAL_LANGUAGE: "false"
    DEFAULT_WORKSPACE: $CI_BUILDS_DIR/$CI_PROJECT_PATH
  except:
    - schedules


# https://stackoverflow.com/a/58618830
build and push image:
  stage: build
  tags:
    - gitlab-org-docker
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - mkdir -p ~/.docker/cli-plugins
    - "wget -O ~/.docker/cli-plugins/docker-buildx \
      \"https://github.com/docker/buildx/releases/download/\
      ${BUILDX_VERSION}/buildx-${BUILDX_VERSION}.linux-amd64\""
    - chmod a+x ~/.docker/cli-plugins/docker-buildx
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    - "echo \"$CI_JOB_TOKEN\" | docker login -u \"$CI_REGISTRY_USER\" \
      --password-stdin $CI_REGISTRY"
  script:
    - docker buildx create --use
    - "docker buildx build \
      --platform ${BUILD_PLATFORMS:-linux/amd64} \
      --tag \"${CI_REGISTRY_IMAGE}/mjpeg-proxy-go:latest\" --push ."
  only:
    - main
