variables:
  BUILDX_VERSION: "v0.9.1"

stages:
  - lint
  - build

superlinter:
  stage: lint
  tags:
    - docker
  image: ghcr.io/github/super-linter:slim-v4
  script:
    - "true"
  variables:
    RUN_LOCAL: "true"
    DEFAULT_WORKSPACE: $CI_BUILDS_DIR/$CI_PROJECT_PATH
  except:
    - schedules


# https://stackoverflow.com/a/58618830
build and push image:
  stage: build
  tags:
    - docker
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - mkdir -p ~/.docker/cli-plugins
    - wget -O ~/.docker/cli-plugins/docker-buildx "https://github.com/docker/buildx/releases/download/${BUILDX_VERSION}/buildx-${BUILDX_VERSION}.linux-amd64"
    - chmod a+x ~/.docker/cli-plugins/docker-buildx
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    - echo "$CI_BUILD_TOKEN" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  script:
    - docker buildx create --use
    - docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6,linux/386 --tag "${CI_REGISTRY_IMAGE}/mjpeg-proxy-go:latest" --push .
  only:
    - main
